# Numpy

In [35]:
import numpy as np


# Create a random array of 3 x 8 Matrix

# Ignore this تجاهلوا هذا 👇

In [36]:
arr = np.random.randint(1,101,24).reshape(3,8)
print(arr)

[[96 12 82 71 64 88 76 10]
 [78 41  5 64 41 61 93 65]
 [ 6 13 94 41 50 84  9 30]]


# Create a Matrix of 3 x 8 ---- 3 Rows; 8 Columns

In [37]:
arr = np.array([[96, 12, 82, 71, 64, 88, 76, 10],
                [78, 41, 5, 64, 41, 61, 93, 65],
                [6, 13, 94, 41, 50, 84, 9, 30]])

In [38]:
print(f"The shape of arr: {arr.shape}")
print(f"The size of arr: {arr.size}")
print(f"Number of dimensions: {arr.ndim}")
print(f"Data Types: {arr.dtype}")

The shape of arr: (3, 8)
The size of arr: 24
Number of dimensions: 2
Data Types: int32


# convert arr to 4x6 matrix

In [39]:
arr.reshape(4,6)

array([[96, 12, 82, 71, 64, 88],
       [76, 10, 78, 41,  5, 64],
       [41, 61, 93, 65,  6, 13],
       [94, 41, 50, 84,  9, 30]])

In [40]:
arr.reshape(12, 2)

array([[96, 12],
       [82, 71],
       [64, 88],
       [76, 10],
       [78, 41],
       [ 5, 64],
       [41, 61],
       [93, 65],
       [ 6, 13],
       [94, 41],
       [50, 84],
       [ 9, 30]])

# Element-wise Operations

In [41]:
arr_a = arr + 2          # Addition
arr_b = arr - 3          # Subtraction
arr_c = arr * 1.6        # Multiplication
arr_d = arr / 2           # Division

In [42]:
print(f"""
Transpose (T) of 3 x 8 Matrix becomes 8 x 3:
{arr.T}
---------------------------------
Original Matrix:
{arr}
""")


Transpose (T) of 3 x 8 Matrix becomes 8 x 3:
[[96 78  6]
 [12 41 13]
 [82  5 94]
 [71 64 41]
 [64 41 50]
 [88 61 84]
 [76 93  9]
 [10 65 30]]
---------------------------------
Original Matrix:
[[96 12 82 71 64 88 76 10]
 [78 41  5 64 41 61 93 65]
 [ 6 13 94 41 50 84  9 30]]



In [43]:
arr.dot(arr.T)

array([[38841, 28644, 22927],
       [28644, 30162, 14056],
       [22927, 14056, 21259]])

In [44]:
arr.T.dot(arr)

array([[15336,  4428,  8826, 12054,  9642, 13710, 14604,  6210],
       [ 4428,  1994,  2411,  4009,  3099,  4649,  4842,  3175],
       [ 8826,  2411, 15585,  9996, 10153, 15417,  7543,  3965],
       [12054,  4009,  9996, 10818,  9218, 13596, 11717,  6100],
       [ 9642,  3099, 10153,  9218,  8277, 12333,  9127,  4805],
       [13710,  4649, 15417, 13596, 12333, 18521, 13117,  7365],
       [14604,  4842,  7543, 11717,  9127, 13117, 14506,  7075],
       [ 6210,  3175,  3965,  6100,  4805,  7365,  7075,  5225]])

# (3, 8) x (8, 3)
# (8, 3) x (3, 8)

# ZERO MATRIX

In [45]:
zero_matrix = np.zeros((2, 6), dtype=int)

In [46]:
zero_matrix

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [47]:
zero_matrix.dtype

dtype('int32')

# ONES MATRIX 

In [48]:
ones_matrix = np.ones((4, 7))

In [49]:
ones_matrix

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

# ONES LIKE:

In [50]:
arr_03 = np.ones_like(arr)

In [51]:
arr_03

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [52]:
arr_03.shape == arr.shape # Same Shape; But different Values.

True

# Indexing

# Select only the thrid coloum

In [53]:
arr[:, 2]

array([82,  5, 94])

# Select the Second Row

In [54]:
arr[1, :]

array([78, 41,  5, 64, 41, 61, 93, 65])

# Select all elements in the second row; only from the second column to the sixth column

In [55]:
arr[1, 1:6]

array([41,  5, 64, 41, 61])

# Make all elements in the Fourth Column equal 0

In [56]:
arr[:, 3] = 0

In [57]:
arr

array([[96, 12, 82,  0, 64, 88, 76, 10],
       [78, 41,  5,  0, 41, 61, 93, 65],
       [ 6, 13, 94,  0, 50, 84,  9, 30]])

# Make all elements in the last row equal 7

In [64]:
arr[-1, :] = -7 # Negative Indexing!

In [65]:
arr

array([[96, 12, 82,  0, 64, 88, 76, 10],
       [78, 41,  5,  0, 41, 61, 93, 65],
       [-7, -7, -7, -7, -7, -7, -7, -7]])

# Numpy Arithmetic and Statistical Functions

# Absolute Value

In [71]:
np.abs(arr) # Only Positive Numbers!

array([[96, 12, 82,  0, 64, 88, 76, 10],
       [78, 41,  5,  0, 41, 61, 93, 65],
       [ 7,  7,  7,  7,  7,  7,  7,  7]])

# Square Root

In [73]:
np.sqrt(arr) # Assuming All Numbers are Positive

<ipython-input-73-ee7fda9f3fb4>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr) # Assuming All Numbers are Positive


array([[9.79795897, 3.46410162, 9.05538514, 0.        , 8.        ,
        9.38083152, 8.71779789, 3.16227766],
       [8.83176087, 6.40312424, 2.23606798, 0.        , 6.40312424,
        7.81024968, 9.64365076, 8.06225775],
       [       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan]])

# Sign of Elements 1, 0, -1

In [76]:
np.sign(arr)

array([[ 1,  1,  1,  0,  1,  1,  1,  1],
       [ 1,  1,  1,  0,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1]])

# Exponetiation

In [77]:
np.exp(arr)

array([[4.92345829e+41, 1.62754791e+05, 4.09399696e+35, 1.00000000e+00,
        6.23514908e+27, 1.65163625e+38, 1.01480039e+33, 2.20264658e+04],
       [7.49841700e+33, 6.39843494e+17, 1.48413159e+02, 1.00000000e+00,
        6.39843494e+17, 3.10429794e+26, 2.45124554e+40, 1.69488924e+28],
       [9.11881966e-04, 9.11881966e-04, 9.11881966e-04, 9.11881966e-04,
        9.11881966e-04, 9.11881966e-04, 9.11881966e-04, 9.11881966e-04]])

# Sort

In [80]:
np.sort(arr) # Sort Each Row Separetly

array([[ 0, 10, 12, 64, 76, 82, 88, 96],
       [ 0,  5, 41, 41, 61, 65, 78, 93],
       [-7, -7, -7, -7, -7, -7, -7, -7]])

# Linear Algebra

# Dot Product